### PR TITLE
allow explicit declaration of passenger version

### LINKED ISSUE #18: 2a979f5 breaks package-installed passnger
When passenger is installed form a package (eg apt-get), passenger is not available in the path so can't get the version number. You can specify this in env variables, however in this instance, running passenger -v, still wouldn't return anything.

Perhaps the option to specify which version of passenger is being used, rather than trying to detect. (or a command that lets you specify the version) eg `dpkg -l | grep passenger` or similar.

### PR DESCRIPTION
**Pull request by yule**
closes #18

### CODE REVIEW

**Comment by gurix** [comment]
:+1: even if in my opinion `passenger_restart_with_touch: true` is enough but it should be available via rubygems.

**Comment by betesh** [comment]
I am waiting for an answer from @yule before releasing a new gem.  If I don't hear from him in the next day or so, I will probably release it and close #18 and #19

**Comment by yule** [comment]
Think `passenger_restart_with_touch` is enough, however would be a nice feature to be able to explicitly state passenger version (useful in future where passenger versions differ on things other than restart mechanism?)

**Comment by betesh** [comment]
We can detect the passenger version on our own.  If there are differences where there's only one way to do things, there's no reason for you to specify the passenger version.  It may not even be the same version on all app servers (for instance, if you're testing the newest version on 1 app server before upgrading on all others).

If it's a version difference that does leave you with a choice, then asking you the version doesn't help--we need to wait until we know what those choices are and then give users true/false options.

**Pull request closed without merging**
