### PR TITLE
Add support for chruby

### PR DESCRIPTION
**Pull request by aeons**
Also give a proper error message when passenger is not found in path.

### CODE REVIEW

**Comment by betesh** [comment]
@aeons I merged the first commit on this branch.  Can you explain what the next 2 commits do?

**Comment by aeons** [comment]
Second commit: If passenger is not in $PATH, then instead of dying with an index out of range error (or something like that), output an error message and then exit.

Third commit: If restart_with_sudo is true, then the command map is only applied to the sudo command and not the following chruby command. This commit makes sure that both parts are command mapped if necessary.

**Comment by betesh** [comment]
Second commit: Wouldn't it be better to `test(:which, :passenger)` right before running `passenger -v`?  If we are concerned that it is not in PATH, that would be the appropriate way to test for it.

Third commit: Tell me more about the environment.  As an RVM user, I can tell you this would do more harm than good, and the right way to do it is with `rvmsudo`.  I don't use CHRuby or RBEnv; is one of those environments where you are running into problems?

**Comment by aeons** [comment]
Second: you are probably right, this is my first time doing anything with capistrano so I just fiddled till it worked.

Third commit: Yes, it's with chruby. I'm not sure how to do this correctly with chruby. 

This is their wiki page on sudo: https://github.com/postmodern/chruby/wiki/Sudo

My problem was that when the command map is only applied to the `sudo` command, then the `chruby-exec` command was not found, since that would have to be command mapped as well.

**Comment by betesh** [comment]
OK I will merge the 3rd commit once I have a chance to test it.  For the 2nd one, if you want us to handle that case more gracefully, please submit a new PR for it.

**Comment by aeons** [comment]
It was for doing dry-run, so 8e9edb55b694f0cd14f3b2350e917ec9ef1db1e2 fixes it for me.

**Comment by betesh** [comment]
@aeons Thanks.  Which commit are you referring to?  The 2nd one?

**Comment by betesh** [comment]
merged 3rd commit.  2nd one no longer needed.

**Pull request closed without merging**
